### ISSUE TITLE
Keepalive timeout exception

### ISSUE THREAD

**Issue by mmartinson** [sanmiguel/websocket_client#54] opened 2017-05-30 17:37 UTC
Not totally sure if this is a bug or a question. I've been using this library as a dependency of [elixir slack](https://github.com/BlakeWilliams/Elixir-Slack) and a number of people have been having [an issue](https://github.com/sanmiguel/websocket_client/issues/54) with this exception. I would be possible to patch that library to handle it if it is an intended exception, but I thought I'd ask since I'm not familiar with the codebase enough know for sure. 

```
exit: ** (exit) {:error, :keepalive_timeout}
File "gen_fsm.erl", line 559, in :gen_fsm.terminate/7
File "proc_lib.erl", line 247, in :proc_lib.init_p_do_apply/3
Module "websocket_client", in :websocket_client.init(:Argument__1)
```

**Comment by sanmiguel** [comment] 2017-06-16 12:52
Sorry to see you're having issues. I'll take a look at the linked issue and see if there's anything we can do in the client to mitigate it. Watch this space!

**Comment by sanmiguel** [comment] 2017-07-19 22:30
Howdy @mmartinson - sorry for the long delay. I've finally had a chance to look into this and think the issue is caused by the return value from the `ondisconnect` callback in the Elixir-Slack `Slack.Bot` module. I've left a comment on the original issue over there explaining how I think it should change to fix it.

I'm going to close this issue for now because this looks like expected behaviour. Please feel free to reopen if there's more that I've missed!

**Closed by sanmiguel** 2017-07-19 22:30 UTC
Labels: bug, in progress
